### ISSUE TITLE
add test for unresolved jjb variables 

### ISSUE THREAD

**Issue by rkhozinov** [rkhozinov/jenkins-jobs#124]
In some cases we have unresolved jjb envs in output xml files.

`{plugin-version}` or so. 

Need to add specific check to the travis to avoid that errors. 

need to check `output` directory

**Comment by rkhozinov** [comment]
@ekhomyakova pls help us

**Comment by naumvd95** [comment]
if grep -R -E '[^$]{[a-zA-Z0-9_-]+}'; then
fi
