### ISSUE TITLE
create matrix for .travis checks

### ISSUE THREAD

**Issue by rkhozinov** [rkhozinov/jenkins-jobs#167]

**Comment by naumvd95** [comment]
@rkhozinov  please clarify info
what "matrix"?
is that plugin?

**Comment by rkhozinov** [comment]
https://docs.travis-ci.com/user/speeding-up-the-build/

**Comment by naumvd95** [comment]
summary
if we use matrix-case, travis will schedule n-builds (depends of env amount)
but in free-version we can't run parralel builds, so its a bad case
quote **Travis CI will determine the build matrix based on the environment variables and schedule two builds to run.**

**Comment by rkhozinov** [comment]
log not speed
