### ISSUE TITLE
multiple refs for fuel-qa repo

### ISSUE THREAD

**Issue by rkhozinov** [rkhozinov/jenkins-jobs#21]
We can't initialize refs with submodule.
So we should apply the "fetching in cycle" method after the fuel-qa submodule initialization. 

```
cd plugin_test/fuel-qa
for ref in $FUEL_QA_REFS; do
  git fetch $ref
done
```

I think we should move git-related logic  to a separate build step.

**Comment by naumvd95** [comment]
https://github.com/rkhozinov/jenkins-jobs/pull/22

**Comment by naumvd95** [comment]
https://github.com/rkhozinov/jenkins-jobs/pull/29
