### ISSUE TITLE
env/diagnostic snapshots should be created after each build

### ISSUE THREAD

**Issue by rkhozinov** [rkhozinov/jenkins-jobs#24]
MAKE_SNAPSHOT=True

**Comment by rkhozinov** [comment]
https://github.com/openstack/fuel-qa/blob/master/fuelweb_test/settings.py#L692

**Comment by rkhozinov** [comment]
https://github.com/openstack/fuel-qa/blob/master/fuelweb_test/settings.py#L439

**Comment by rkhozinov** [comment]
@naumvd95 please attach a pull-request or a commit here

**Comment by rkhozinov** [comment]
I've seen that you've already resolved that issue

**Comment by naumvd95** [comment]
https://github.com/rkhozinov/jenkins-jobs/pull/37
