### ISSUE TITLE
Add job for UI tests with fake nailgun

### ISSUE THREAD

**Issue by ekhomyakova** [rkhozinov/jenkins-jobs#283]
Configuration for docker compose: https://github.com/ekhomyakova/fuel-ui-tests-docker/tree/fake-ui

Job configuration may be similar to UI tests on real nailgun, but:
* Instead of TEST_PREFIX should be TEST_PATH variable
* Near the fuel-ui should be fuel-web repo (stable/newton branch), both repos should be downloaded to the directory with docker-compose file (fuel-ui-tests-docker)
* There is no 10.x iso/env needed

TEST_PATH alternatives:
* static/tests/functional/nightly/test_cluster_workflows.js 
* static/tests/functional/nightly/test_deployment_history.js

**Comment by rkhozinov** [comment]
@naumvd95 please see #284

**Comment by naumvd95** [comment]
@rkhozinov technically we already resolved this issue

**Comment by naumvd95** [comment]
@rkhozinov @ekhomyakova seems we need to merge branch and close issue
anybody have different decisions?
