### ISSUE TITLE
Fix fake-ui job

### ISSUE THREAD

**Issue by ekhomyakova** [rkhozinov/jenkins-jobs#310]
http://jenkins-tpi.bud.mirantis.net:8080/job/10.0.ui-fake.test_deployment_history/143/artifact/docker/fuel-ui/test_run/ui_func/firefox_on_any_platform_-_Workflows_-_14%3A54%3A43_GMT-0700_(PDT).png

**Comment by rkhozinov** [comment]
@naumvd95 has it been fixed?
